#!/usr/bin/env node
// Generates ui/tokens.css from design/tokens.json.
//
// `render(tokens)` is pure: it takes the parsed tokens and returns the CSS string, so the test can
// assert the committed ui/tokens.css is byte-identical to it. Running this file as a script writes
// the file. Nothing else in ui/ may hard-code a colour, radius or spacing step: everything comes
// from the custom properties emitted here.
//
//   node ui/scripts/build-tokens.mjs

import { writeFileSync, readFileSync } from 'node:fs';

/** `bg_soft` -> `--bg-soft` */
const prop = (key) => '--' + key.replaceAll('_', '-');

/** One `--key: value;` line, indented two spaces. */
const line = (key, value) => `  ${prop(key)}: ${value};\n`;

/** The colour block for one theme, in design/tokens.json key order. */
function colours(theme) {
  return Object.entries(theme).map(([k, v]) => line(k, v)).join('');
}

/**
 * Render the whole stylesheet. Pure — same input, same bytes out.
 * @param {object} tokens parsed design/tokens.json
 * @returns {string} CSS
 */
export function render(tokens) {
  const { dark, light, field, radius, spacing, type, layout } = tokens;

  const fontStack =
    '"Inter var", "Inter", -apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif';
  const monoStack =
    '"JetBrains Mono var", "JetBrains Mono", ui-monospace, "SF Mono", Menlo, Consolas, "Roboto Mono", monospace';
  // The pixel face falls back to the mono stack, not the sans: a balance must stay tabular.
  const displayStack = `"Departure Mono", ${monoStack}`;

  let css = '';
  css += `/* ${tokens.name} design tokens — GENERATED by ui/scripts/build-tokens.mjs.\n`;
  css += `   Edit design/tokens.json and re-run the script; never edit this file by hand.\n`;
  css += `   Dark is the default theme. \`html[data-theme="light"]\` forces light, and\n`;
  css += `   \`html[data-theme="system"]\` follows the operating system. */\n`;

  // Self-hosted variable fonts. No network: the shells run under CSP script-src/style-src 'self'.
  css += `\n@font-face {\n`;
  css += `  font-family: "Inter var";\n`;
  css += `  font-style: normal;\n`;
  css += `  font-weight: 100 900;\n`;
  css += `  font-display: swap;\n`;
  css += `  src: url("fonts/Inter-Variable.woff2") format("woff2");\n`;
  css += `}\n`;
  css += `@font-face {\n`;
  css += `  font-family: "JetBrains Mono var";\n`;
  css += `  font-style: normal;\n`;
  css += `  font-weight: 100 800;\n`;
  css += `  font-display: swap;\n`;
  css += `  src: url("fonts/JetBrainsMono-Variable.woff2") format("woff2");\n`;
  css += `}\n`;
  css += `@font-face {\n`;
  css += `  font-family: "Departure Mono";\n`;
  css += `  font-style: normal;\n`;
  css += `  font-weight: 400;\n`;
  css += `  font-display: swap;\n`;
  css += `  src: url("fonts/DepartureMono-Regular.woff2") format("woff2");\n`;
  css += `}\n`;

  // Dark — the default.
  css += `\n:root {\n`;
  css += `  color-scheme: dark;\n`;
  css += colours(dark);
  css += `\n`;
  // The entropy field is theme-independent: ink with bone grain in both themes.
  css += `  --field-ink: ${field.ink};\n`;
  css += `  --field-ink-2: ${field.ink_2};\n`;
  css += `  --field-grain: ${field.grain};\n`;
  css += `\n`;
  for (const [k, v] of Object.entries(radius)) css += `  --r-${k}: ${v}px;\n`;
  css += `\n`;
  spacing.forEach((v, i) => { css += `  --s-${i + 1}: ${v}px;\n`; });
  css += `\n`;
  css += `  --font: ${fontStack};\n`;
  css += `  --mono: ${monoStack};\n`;
  css += `  --display: ${displayStack};\n`;
  for (const [k, v] of Object.entries(type)) {
    if (typeof v !== 'object') continue;
    css += `  --fs-${k}: ${v.size}px;\n`;
    css += `  --fw-${k}: ${v.weight};\n`;
  }
  css += `\n`;
  css += `  --popup-w: ${layout.extension_popup.width}px;\n`;
  css += `  --popup-h: ${layout.extension_popup.height}px;\n`;
  css += `  --tap: ${layout.touch_target_min}px;\n`;
  css += `  --wide-at: 900px;\n`;
  css += `}\n`;

  // Light, chosen explicitly.
  css += `\n:root[data-theme="light"] {\n`;
  css += `  color-scheme: light;\n`;
  css += colours(light);
  css += `}\n`;

  // Light, following the operating system.
  css += `\n@media (prefers-color-scheme: light) {\n`;
  css += `  :root[data-theme="system"] {\n`;
  css += `    color-scheme: light;\n`;
  css += colours(light).replace(/^ {2}/gm, '    ');
  css += `  }\n`;
  css += `}\n`;

  return css;
}

// Written only when run directly, so importing the module stays side-effect free.
if (import.meta.url === `file://${process.argv[1]}`) {
  const tokensUrl = new URL('../../design/tokens.json', import.meta.url);
  const outUrl = new URL('../tokens.css', import.meta.url);
  const tokens = JSON.parse(readFileSync(tokensUrl, 'utf8'));
  writeFileSync(outUrl, render(tokens));
  console.log(`wrote ${outUrl.pathname}`);
}
