// GENERATED by ui/scripts/extract-strings.mjs — do not edit. Every English string the wallet
// can show, as the `t()` call sites write it; the value is the key, since English is the
// source language. Each other language is ui/locales/<code>.js, with the same keys: a string
// value, or an object of CLDR plural categories ({one, few, many, other}) for a key with an
// {n} hole whose translation inflects by number. `{name}` holes and the words in the glossary
// at the top of each dictionary are kept as they are.
// 25 strings.
export default {
  "{n} d ago": "{n} d ago",
  "{n} h ago": "{n} h ago",
  "{n} min ago": "{n} min ago",
  "1 hour": "1 hour",
  "1 minute": "1 minute",
  "15 minutes": "15 minutes",
  "5 minutes": "5 minutes",
  "Activity": "Activity",
  "Appearance": "Appearance",
  "Chain {id}": "Chain {id}",
  "Dark": "Dark",
  "Device language": "Device language",
  "Explore": "Explore",
  "Home": "Home",
  "just now": "just now",
  "Language": "Language",
  "Light": "Light",
  "Never": "Never",
  "Not connected": "Not connected",
  "Settings": "Settings",
  "System": "System",
  "The language could not be saved.": "The language could not be saved.",
  "Theme": "Theme",
  "Today": "Today",
  "Yesterday": "Yesterday",
};
